name: chat-cognos-io

services:
  web:
    build: ./web
    restart: unless-stopped
    environment:
      CADDY_ADMIN: "unix//run/caddy/admin.sock"
    env_file:
      - ./web/.env
    networks:
      - backend
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./web/Caddyfile:/etc/caddy/Caddyfile
      - web-data:/data
      - web-config:/config

  backend:
    build: ./backend
    restart: unless-stopped
    user: "1001:0"
    env_file:
      - ./backend/.env
    environment:
      COGNOS_INFOMANIAK_API_KEY_FILE: /run/secrets/infomaniak_api_key
    networks:
      - backend
    ports: []
    volumes:
      - db-data:/home/appuser/pb_data
    secrets:
      - infomaniak_api_key

  backup:
    image: ghcr.io/borgmatic-collective/borgmatic
    restart: unless-stopped
    env_file:
      - ./backup/.env
    environment:
      BORG_PASSPHRASE_FILE: /run/secrets/borg_passphrase
      BORG_RSH: ssh -i /run/secrets/borg_ssh_key -o IdentitiesOnly=yes -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/run/secrets/borg_known_hosts
    volumes:
      - web-data:/source/caddy-data:ro # Caddy data
      - web-config:/source/caddy-config:ro # Caddy configuration
      - db-data:/cognos-db # Pocketbase SQLite database
      - ./backup/borgmatic.d:/etc/borgmatic.d:ro # Borgmatic configuration
    secrets:
      - borg_passphrase
      - borg_ssh_key
      - borg_known_hosts

volumes:
  # Stores Caddy TLS certificates and other data
  # https://caddyserver.com/docs/conventions#data-directory
  web-data:
  web-config:
  db-data:

networks:
  backend:

secrets:
  infomaniak_api_key:
    file: ./backend/secrets/infomaniak_api_key
  borg_passphrase:
    file: ./backup/secrets/borg_passphrase
  borg_ssh_key:
    file: ./backup/secrets/borg_ssh_key
  borg_known_hosts:
    file: ./backup/secrets/borg_known_hosts
