package migrations

import (
	"github.com/pocketbase/pocketbase/core"
	m "github.com/pocketbase/pocketbase/migrations"
)

// Seed the Requesty.ai EU gateway catalogue. Region-bearing ids are
// normalised to the @eu meta-region; Requesty load-balances / falls back
// across the underlying EU regions behind it. eu-geolocation models are
// tagged privacy_tier=eu; europe-pinned models whose processing Requesty
// flags as global are privacy_tier=global. Image-generation and Responses
// API variants are seeded but left un-whitelisted until those flows ship.
type requestyModelSeed struct {
	modelID            string
	providerModelID    string
	name               string
	privacyTier        string
	enabled            bool
	whitelisted        bool
	isOpenSource       bool
	inputContextTokens int
	maxOutputTokens    int
	inputUSD           float64
	outputUSD          float64
	tagSlugs           []string
}

func init() {
	m.Register(func(app core.App) error {
		provider, err := findOrCreateRecord(app, "ai_providers", "provider_id", "requesty", map[string]any{
			"name":                "Requesty",
			"description":         "Requesty.ai routes models through a zero-data-retention EU gateway hosted in Frankfurt.",
			"enabled":             true,
			"routing_provider_id": "requesty",
		})
		if err != nil {
			return err
		}

		tagsBySlug := map[string]string{}
		for _, tag := range []struct {
			slug     string
			title    string
			category string
		}{
			{slug: "general-purpose", title: "general-purpose", category: "capability"},
			{slug: "image-generation", title: "Image generation", category: "capability"},
			{slug: "reasoning", title: "Reasoning", category: "capability"},
			{slug: "vision", title: "Vision", category: "capability"},
			{slug: "europe", title: "Europe", category: "residency"},
		} {
			record, err := findOrCreateRecord(app, "ai_tags", "slug", tag.slug, map[string]any{
				"title":    tag.title,
				"category": tag.category,
			})
			if err != nil {
				return err
			}
			tagsBySlug[tag.slug] = record.Id
		}

		for _, model := range []requestyModelSeed{
			{
				modelID:            "nebius-meta-llama-llama-3-3-70b-instruct",
				providerModelID:    "nebius/meta-llama/Llama-3.3-70B-Instruct",
				name:               "Llama 3.3 70B Instruct",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       true,
				inputContextTokens: 128000,
				maxOutputTokens:    0,
				inputUSD:           0.13,
				outputUSD:          0.4,
				tagSlugs:           []string{"europe", "general-purpose"},
			},
			{
				modelID:            "nebius-moonshotai-kimi-k2-5",
				providerModelID:    "nebius/moonshotai/kimi-k2.5",
				name:               "Kimi K2.5 (Nebius)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       true,
				inputContextTokens: 256000,
				maxOutputTokens:    128000,
				inputUSD:           0.5,
				outputUSD:          2.5,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "nebius-google-gemma-3-27b-it",
				providerModelID:    "nebius/google/gemma-3-27b-it",
				name:               "Gemma 3 27B IT",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       true,
				inputContextTokens: 128000,
				maxOutputTokens:    8192,
				inputUSD:           0.1,
				outputUSD:          0.3,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning"},
			},
			{
				modelID:            "nebius-nousresearch-hermes-4-405b",
				providerModelID:    "nebius/nousresearch/hermes-4-405b",
				name:               "Hermes 4 405B",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       true,
				inputContextTokens: 128000,
				maxOutputTokens:    0,
				inputUSD:           1.0,
				outputUSD:          3.0,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning"},
			},
			{
				modelID:            "nebius-glm-5-2",
				providerModelID:    "nebius/glm-5.2",
				name:               "GLM 5.2",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       true,
				inputContextTokens: 1000000,
				maxOutputTokens:    131072,
				inputUSD:           1.4,
				outputUSD:          4.4,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning"},
			},
			{
				modelID:            "nebius-qwen-qwen3-235b-a22b-instruct-2507",
				providerModelID:    "nebius/qwen/qwen3-235b-a22b-instruct-2507",
				name:               "Qwen3 235B A22B Instruct 2507",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       true,
				inputContextTokens: 128000,
				maxOutputTokens:    0,
				inputUSD:           0.2,
				outputUSD:          0.6,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning"},
			},
			{
				modelID:            "nebius-openai-gpt-oss-120b",
				providerModelID:    "nebius/openai/gpt-oss-120b",
				name:               "GPT-OSS 120B",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       true,
				inputContextTokens: 131000,
				maxOutputTokens:    128000,
				inputUSD:           0.15,
				outputUSD:          0.6,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning"},
			},
			{
				modelID:            "nebius-qwen-qwen3-30b-a3b-instruct-2507",
				providerModelID:    "nebius/qwen/qwen3-30b-a3b-instruct-2507",
				name:               "Qwen3 30B A3B Instruct 2507",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       true,
				inputContextTokens: 128000,
				maxOutputTokens:    0,
				inputUSD:           0.1,
				outputUSD:          0.3,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning"},
			},
			{
				modelID:            "nebius-qwen-qwen3-next-80b-a3b-thinking",
				providerModelID:    "nebius/qwen/qwen3-next-80b-a3b-thinking",
				name:               "Qwen3 Next 80B A3B Thinking",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       true,
				inputContextTokens: 128000,
				maxOutputTokens:    0,
				inputUSD:           0.15,
				outputUSD:          1.2,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning"},
			},
			{
				modelID:            "nebius-nousresearch-hermes-4-70b",
				providerModelID:    "nebius/nousresearch/hermes-4-70b",
				name:               "Hermes 4 70B",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       true,
				inputContextTokens: 128000,
				maxOutputTokens:    0,
				inputUSD:           0.13,
				outputUSD:          0.4,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning"},
			},
			{
				modelID:            "nebius-qwen-qwen3-32b",
				providerModelID:    "nebius/qwen/qwen3-32b",
				name:               "Qwen3 32B",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       true,
				inputContextTokens: 128000,
				maxOutputTokens:    0,
				inputUSD:           0.1,
				outputUSD:          0.3,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning"},
			},
			{
				modelID:            "nebius-nvidia-nemotron-3-nano-omni",
				providerModelID:    "nebius/nvidia/nemotron-3-nano-omni",
				name:               "Nemotron 3 Nano Omni",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       true,
				inputContextTokens: 300000,
				maxOutputTokens:    0,
				inputUSD:           0.06,
				outputUSD:          0.24,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning"},
			},
			{
				modelID:            "nebius-zai-org-glm-5-1",
				providerModelID:    "nebius/zai-org/glm-5.1",
				name:               "GLM 5.1 (Nebius)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       true,
				inputContextTokens: 200000,
				maxOutputTokens:    0,
				inputUSD:           1.4,
				outputUSD:          4.4,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning"},
			},
			{
				modelID:            "vertex-gemini-2-5-flash",
				providerModelID:    "vertex/gemini-2.5-flash@eu",
				name:               "Gemini 2.5 Flash (Vertex)",
				privacyTier:        "global",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 1048576,
				maxOutputTokens:    65535,
				inputUSD:           0.3,
				outputUSD:          2.5,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "vertex-claude-opus-4-8",
				providerModelID:    "vertex/claude-opus-4-8@eu",
				name:               "Claude Opus 4.8 (Vertex)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 1000000,
				maxOutputTokens:    128000,
				inputUSD:           5.5,
				outputUSD:          27.5,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "vertex-gemini-2-5-flash-image",
				providerModelID:    "vertex/gemini-2.5-flash-image@eu",
				name:               "Gemini 2.5 Flash Image",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        false,
				isOpenSource:       false,
				inputContextTokens: 1048576,
				maxOutputTokens:    65535,
				inputUSD:           0.3,
				outputUSD:          2.5,
				tagSlugs:           []string{"europe", "image-generation", "reasoning", "vision"},
			},
			{
				modelID:            "vertex-gemini-2-5-pro",
				providerModelID:    "vertex/gemini-2.5-pro@eu",
				name:               "Gemini 2.5 Pro (Vertex)",
				privacyTier:        "global",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 1048576,
				maxOutputTokens:    65535,
				inputUSD:           1.25,
				outputUSD:          10.0,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "vertex-gemini-2-5-flash-lite",
				providerModelID:    "vertex/gemini-2.5-flash-lite@eu",
				name:               "Gemini 2.5 Flash Lite",
				privacyTier:        "global",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 1048576,
				maxOutputTokens:    65535,
				inputUSD:           0.1,
				outputUSD:          0.4,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "vertex-gemini-3-5-flash",
				providerModelID:    "vertex/gemini-3.5-flash@eu",
				name:               "Gemini 3.5 Flash",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 1048576,
				maxOutputTokens:    65535,
				inputUSD:           1.5,
				outputUSD:          9.0,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "vertex-claude-opus-4-5",
				providerModelID:    "vertex/claude-opus-4-5@eu",
				name:               "Claude Opus 4.5 (Vertex)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 200000,
				maxOutputTokens:    64000,
				inputUSD:           5.5,
				outputUSD:          27.5,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "vertex-claude-sonnet-4",
				providerModelID:    "vertex/claude-sonnet-4@eu",
				name:               "Claude Sonnet 4 (Vertex)",
				privacyTier:        "global",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 200000,
				maxOutputTokens:    64000,
				inputUSD:           3.0,
				outputUSD:          15.0,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "vertex-claude-opus-4-6",
				providerModelID:    "vertex/claude-opus-4-6@eu",
				name:               "Claude Opus 4.6",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 1000000,
				maxOutputTokens:    128000,
				inputUSD:           5.5,
				outputUSD:          27.5,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "vertex-gemini-3-1-flash-lite",
				providerModelID:    "vertex/gemini-3.1-flash-lite@eu",
				name:               "Gemini 3.1 Flash Lite",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 1048576,
				maxOutputTokens:    65535,
				inputUSD:           0.25,
				outputUSD:          1.5,
				tagSlugs:           []string{"europe", "general-purpose", "vision"},
			},
			{
				modelID:            "vertex-claude-sonnet-4-6",
				providerModelID:    "vertex/claude-sonnet-4-6@eu",
				name:               "Claude Sonnet 4.6 (Vertex)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 1000000,
				maxOutputTokens:    128000,
				inputUSD:           3.0,
				outputUSD:          15.0,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "vertex-claude-opus-4-7",
				providerModelID:    "vertex/claude-opus-4-7@eu",
				name:               "Claude Opus 4.7 (Vertex)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 1000000,
				maxOutputTokens:    128000,
				inputUSD:           5.5,
				outputUSD:          27.5,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "vertex-claude-haiku-4-5",
				providerModelID:    "vertex/claude-haiku-4-5@eu",
				name:               "Claude Haiku 4.5 (Vertex)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 200000,
				maxOutputTokens:    64000,
				inputUSD:           1.1,
				outputUSD:          5.5,
				tagSlugs:           []string{"europe", "general-purpose", "vision"},
			},
			{
				modelID:            "vertex-claude-sonnet-4-5",
				providerModelID:    "vertex/claude-sonnet-4-5@eu",
				name:               "Claude Sonnet 4.5 (Vertex)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 200000,
				maxOutputTokens:    64000,
				inputUSD:           3.3,
				outputUSD:          16.5,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "azure-gpt-4-1-nano",
				providerModelID:    "azure/gpt-4.1-nano@eu",
				name:               "GPT-4.1 Nano",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 1047576,
				maxOutputTokens:    32768,
				inputUSD:           0.1,
				outputUSD:          0.4,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "azure-gpt-5",
				providerModelID:    "azure/gpt-5@eu",
				name:               "GPT-5",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 200000,
				maxOutputTokens:    100000,
				inputUSD:           1.25,
				outputUSD:          10.0,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "azure-openai-responses-gpt-5-4",
				providerModelID:    "azure/openai-responses/gpt-5.4@eu",
				name:               "GPT-5.4 (Responses)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        false,
				isOpenSource:       false,
				inputContextTokens: 1050000,
				maxOutputTokens:    128000,
				inputUSD:           2.5,
				outputUSD:          15.0,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "azure-openai-responses-gpt-4-1",
				providerModelID:    "azure/openai-responses/gpt-4.1@eu",
				name:               "GPT-4.1 (Responses)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        false,
				isOpenSource:       false,
				inputContextTokens: 1047576,
				maxOutputTokens:    32768,
				inputUSD:           2.0,
				outputUSD:          8.0,
				tagSlugs:           []string{"europe", "general-purpose", "vision"},
			},
			{
				modelID:            "azure-openai-responses-gpt-4-1-nano",
				providerModelID:    "azure/openai-responses/gpt-4.1-nano@eu",
				name:               "GPT-4.1 Nano (Responses)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        false,
				isOpenSource:       false,
				inputContextTokens: 1047576,
				maxOutputTokens:    32768,
				inputUSD:           0.1,
				outputUSD:          0.4,
				tagSlugs:           []string{"europe", "general-purpose", "vision"},
			},
			{
				modelID:            "azure-gpt-5-nano",
				providerModelID:    "azure/gpt-5-nano@eu",
				name:               "GPT-5 Nano",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 200000,
				maxOutputTokens:    100000,
				inputUSD:           0.05,
				outputUSD:          0.4,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning"},
			},
			{
				modelID:            "azure-gpt-5-4",
				providerModelID:    "azure/gpt-5.4@eu",
				name:               "GPT-5.4",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 1050000,
				maxOutputTokens:    128000,
				inputUSD:           2.5,
				outputUSD:          15.0,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "azure-o4-mini",
				providerModelID:    "azure/o4-mini@eu",
				name:               "o4 Mini",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 200000,
				maxOutputTokens:    100000,
				inputUSD:           1.1,
				outputUSD:          4.4,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning"},
			},
			{
				modelID:            "azure-gpt-5-1",
				providerModelID:    "azure/gpt-5.1@eu",
				name:               "GPT-5.1",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 200000,
				maxOutputTokens:    100000,
				inputUSD:           1.25,
				outputUSD:          10.0,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "azure-gpt-4-1",
				providerModelID:    "azure/gpt-4.1@eu",
				name:               "GPT-4.1",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 1047576,
				maxOutputTokens:    32768,
				inputUSD:           2.0,
				outputUSD:          8.0,
				tagSlugs:           []string{"europe", "general-purpose", "vision"},
			},
			{
				modelID:            "azure-gpt-5-mini",
				providerModelID:    "azure/gpt-5-mini@eu",
				name:               "GPT-5 Mini",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 200000,
				maxOutputTokens:    100000,
				inputUSD:           0.25,
				outputUSD:          2.0,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning"},
			},
			{
				modelID:            "azure-openai-responses-gpt-5-5",
				providerModelID:    "azure/openai-responses/gpt-5.5@eu",
				name:               "GPT-5.5 (Responses)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        false,
				isOpenSource:       false,
				inputContextTokens: 1050000,
				maxOutputTokens:    128000,
				inputUSD:           5.0,
				outputUSD:          30.0,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "azure-openai-responses-gpt-4-1-mini",
				providerModelID:    "azure/openai-responses/gpt-4.1-mini@eu",
				name:               "GPT-4.1 Mini (Responses)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        false,
				isOpenSource:       false,
				inputContextTokens: 1047576,
				maxOutputTokens:    32768,
				inputUSD:           0.4,
				outputUSD:          1.6,
				tagSlugs:           []string{"europe", "general-purpose", "vision"},
			},
			{
				modelID:            "azure-gpt-4o-mini",
				providerModelID:    "azure/gpt-4o-mini@eu",
				name:               "GPT-4o Mini",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 128000,
				maxOutputTokens:    16000,
				inputUSD:           0.15,
				outputUSD:          0.6,
				tagSlugs:           []string{"europe", "general-purpose", "vision"},
			},
			{
				modelID:            "azure-gpt-4-1-mini",
				providerModelID:    "azure/gpt-4.1-mini@eu",
				name:               "GPT-4.1 Mini",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 1047576,
				maxOutputTokens:    32768,
				inputUSD:           0.4,
				outputUSD:          1.6,
				tagSlugs:           []string{"europe", "general-purpose", "vision"},
			},
			{
				modelID:            "azure-gpt-5-5",
				providerModelID:    "azure/gpt-5.5@eu",
				name:               "GPT-5.5",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 1050000,
				maxOutputTokens:    128000,
				inputUSD:           5.0,
				outputUSD:          30.0,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "bedrock-kimi-k2-5",
				providerModelID:    "bedrock/kimi-k2.5@eu",
				name:               "Kimi K2.5 (Bedrock)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       true,
				inputContextTokens: 128000,
				maxOutputTokens:    16000,
				inputUSD:           0.72,
				outputUSD:          3.6,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "bedrock-claude-sonnet-4",
				providerModelID:    "bedrock/claude-sonnet-4@eu",
				name:               "Claude Sonnet 4 (Bedrock)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 200000,
				maxOutputTokens:    64000,
				inputUSD:           3.0,
				outputUSD:          15.0,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "bedrock-claude-sonnet-4-5",
				providerModelID:    "bedrock/claude-sonnet-4-5@eu",
				name:               "Claude Sonnet 4.5 (Bedrock)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 200000,
				maxOutputTokens:    64000,
				inputUSD:           3.3,
				outputUSD:          16.5,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "bedrock-claude-opus-4-5",
				providerModelID:    "bedrock/claude-opus-4-5@eu",
				name:               "Claude Opus 4.5 (Bedrock)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 200000,
				maxOutputTokens:    64000,
				inputUSD:           5.5,
				outputUSD:          27.5,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "bedrock-claude-opus-4-7",
				providerModelID:    "bedrock/claude-opus-4-7@eu",
				name:               "Claude Opus 4.7 (Bedrock)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 1000000,
				maxOutputTokens:    128000,
				inputUSD:           5.5,
				outputUSD:          27.5,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "bedrock-claude-opus-4-8",
				providerModelID:    "bedrock/claude-opus-4-8@eu",
				name:               "Claude Opus 4.8 (Bedrock)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 1000000,
				maxOutputTokens:    128000,
				inputUSD:           5.5,
				outputUSD:          27.5,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "bedrock-minimax-m2-5",
				providerModelID:    "bedrock/minimax-m2.5@eu",
				name:               "MiniMax M2.5 (Bedrock)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       true,
				inputContextTokens: 128000,
				maxOutputTokens:    16000,
				inputUSD:           0.36,
				outputUSD:          1.44,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning"},
			},
			{
				modelID:            "bedrock-claude-sonnet-4-6",
				providerModelID:    "bedrock/claude-sonnet-4-6@eu",
				name:               "Claude Sonnet 4.6 (Bedrock)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 1000000,
				maxOutputTokens:    64000,
				inputUSD:           3.3,
				outputUSD:          16.5,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "bedrock-claude-haiku-4-5",
				providerModelID:    "bedrock/claude-haiku-4-5@eu",
				name:               "Claude Haiku 4.5 (Bedrock)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 200000,
				maxOutputTokens:    64000,
				inputUSD:           1.1,
				outputUSD:          5.5,
				tagSlugs:           []string{"europe", "general-purpose", "vision"},
			},
			{
				modelID:            "coding-gemini-2-5-pro",
				providerModelID:    "coding/gemini-2.5-pro@eu",
				name:               "Gemini 2.5 Pro (Coding)",
				privacyTier:        "global",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 1048576,
				maxOutputTokens:    65535,
				inputUSD:           1.25,
				outputUSD:          10.0,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "coding-gemini-2-5-flash",
				providerModelID:    "coding/gemini-2.5-flash@eu",
				name:               "Gemini 2.5 Flash (Coding)",
				privacyTier:        "global",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       false,
				inputContextTokens: 1048576,
				maxOutputTokens:    65535,
				inputUSD:           0.3,
				outputUSD:          2.5,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
			{
				modelID:            "inceptron-glm-5-1",
				providerModelID:    "inceptron/glm-5.1",
				name:               "GLM 5.1 (Inceptron)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       true,
				inputContextTokens: 202752,
				maxOutputTokens:    202752,
				inputUSD:           1.4,
				outputUSD:          4.4,
				tagSlugs:           []string{"europe", "general-purpose"},
			},
			{
				modelID:            "inceptron-minimax-m2-5",
				providerModelID:    "inceptron/minimax-m2.5",
				name:               "MiniMax M2.5 (Inceptron)",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       true,
				inputContextTokens: 196608,
				maxOutputTokens:    196608,
				inputUSD:           0.28,
				outputUSD:          1.1,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning"},
			},
			{
				modelID:            "inceptron-kimi-k2-6",
				providerModelID:    "inceptron/kimi-k2.6",
				name:               "Kimi K2.6",
				privacyTier:        "eu",
				enabled:            true,
				whitelisted:        true,
				isOpenSource:       true,
				inputContextTokens: 262144,
				maxOutputTokens:    262144,
				inputUSD:           0.8,
				outputUSD:          3.5,
				tagSlugs:           []string{"europe", "general-purpose", "reasoning", "vision"},
			},
		} {
			tagIDs := make([]string, 0, len(model.tagSlugs))
			for _, slug := range model.tagSlugs {
				if id, ok := tagsBySlug[slug]; ok {
					tagIDs = append(tagIDs, id)
				}
			}

			fields := map[string]any{
				"provider":                      provider.Id,
				"provider_model_id":             model.providerModelID,
				"name":                          model.name,
				"slug":                          model.modelID,
				"description":                   model.name + " via Requesty's EU gateway with zero data retention.",
				"enabled":                       model.enabled,
				"whitelisted":                   model.whitelisted,
				"privacy_tier":                  model.privacyTier,
				"hosting_country":               "EU",
				"hosting_region":                "eu",
				"no_retention":                  true,
				"is_open_source":                model.isOpenSource,
				"input_context_tokens":          model.inputContextTokens,
				"input_usd_per_million_tokens":  model.inputUSD,
				"output_usd_per_million_tokens": model.outputUSD,
				"tags":                          tagIDs,
			}
			if model.maxOutputTokens > 0 {
				fields["max_output_tokens"] = model.maxOutputTokens
			}

			if _, err := findOrCreateRecord(app, "ai_models", "model_id", model.modelID, fields); err != nil {
				return err
			}
		}

		return nil
	}, func(app core.App) error {
		for _, modelID := range []string{
			"nebius-meta-llama-llama-3-3-70b-instruct",
			"nebius-moonshotai-kimi-k2-5",
			"nebius-google-gemma-3-27b-it",
			"nebius-nousresearch-hermes-4-405b",
			"nebius-glm-5-2",
			"nebius-qwen-qwen3-235b-a22b-instruct-2507",
			"nebius-openai-gpt-oss-120b",
			"nebius-qwen-qwen3-30b-a3b-instruct-2507",
			"nebius-qwen-qwen3-next-80b-a3b-thinking",
			"nebius-nousresearch-hermes-4-70b",
			"nebius-qwen-qwen3-32b",
			"nebius-nvidia-nemotron-3-nano-omni",
			"nebius-zai-org-glm-5-1",
			"vertex-gemini-2-5-flash",
			"vertex-claude-opus-4-8",
			"vertex-gemini-2-5-flash-image",
			"vertex-gemini-2-5-pro",
			"vertex-gemini-2-5-flash-lite",
			"vertex-gemini-3-5-flash",
			"vertex-claude-opus-4-5",
			"vertex-claude-sonnet-4",
			"vertex-claude-opus-4-6",
			"vertex-gemini-3-1-flash-lite",
			"vertex-claude-sonnet-4-6",
			"vertex-claude-opus-4-7",
			"vertex-claude-haiku-4-5",
			"vertex-claude-sonnet-4-5",
			"azure-gpt-4-1-nano",
			"azure-gpt-5",
			"azure-openai-responses-gpt-5-4",
			"azure-openai-responses-gpt-4-1",
			"azure-openai-responses-gpt-4-1-nano",
			"azure-gpt-5-nano",
			"azure-gpt-5-4",
			"azure-o4-mini",
			"azure-gpt-5-1",
			"azure-gpt-4-1",
			"azure-gpt-5-mini",
			"azure-openai-responses-gpt-5-5",
			"azure-openai-responses-gpt-4-1-mini",
			"azure-gpt-4o-mini",
			"azure-gpt-4-1-mini",
			"azure-gpt-5-5",
			"bedrock-kimi-k2-5",
			"bedrock-claude-sonnet-4",
			"bedrock-claude-sonnet-4-5",
			"bedrock-claude-opus-4-5",
			"bedrock-claude-opus-4-7",
			"bedrock-claude-opus-4-8",
			"bedrock-minimax-m2-5",
			"bedrock-claude-sonnet-4-6",
			"bedrock-claude-haiku-4-5",
			"coding-gemini-2-5-pro",
			"coding-gemini-2-5-flash",
			"inceptron-glm-5-1",
			"inceptron-minimax-m2-5",
			"inceptron-kimi-k2-6",
		} {
			record, err := app.FindFirstRecordByData("ai_models", "model_id", modelID)
			if err != nil {
				continue
			}
			if err := app.Delete(record); err != nil {
				return err
			}
		}
		return nil
	})
}
