import {
  BatteryMedium,
  BookText,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Cloud,
  Copy,
  CopyPlus,
  Download,
  Eraser,
  EyeOff,
  File,
  FileText,
  Folder,
  FolderLock,
  FolderPlus,
  GitBranch,
  GraduationCap,
  HardDrive,
  Image,
  Info,
  KeyRound,
  Landmark,
  Languages,
  Laptop,
  LayoutGrid,
  Link,
  List,
  Loader,
  Lock,
  Mail,
  Menu,
  MessageSquare,
  MonitorSmartphone,
  Moon,
  MoreHorizontal,
  Music,
  Paperclip,
  Pause,
  Pencil,
  Pin,
  Play,
  Plus,
  Quote,
  RefreshCw,
  RotateCw,
  Scale,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  ShieldX,
  Signal,
  Sparkles,
  Sun,
  Table,
  ThumbsUp,
  TriangleAlert,
  Type,
  Upload,
  UploadCloud,
  UserPlus,
  Users,
  Wifi,
  X,
} from 'lucide';

export const cognosIconNames = Object.freeze([
  'lock',
  'shield-check',
  'shield',
  'key-round',
  'eye-off',
  'search',
  'laptop',
  'plus',
  'message-square',
  'send',
  'paperclip',
  'book-text',
  'sparkles',
  'server',
  'cloud',
  'folder',
  'git-branch',
  'landmark',
  'graduation-cap',
  'users',
  'user-plus',
  'menu',
  'more-horizontal',
  'chevron-right',
  'chevron-down',
  'chevron-left',
  'x',
  'check',
  'pencil',
  'settings',
  'rotate-cw',
  'copy',
  'copy-plus',
  'refresh-cw',
  'thumbs-up',
  'quote',
  'pin',
  'link',
  'mail',
  'monitor-smartphone',
  'eraser',
  'scale',
  'languages',
  'table',
  'signal',
  'wifi',
  'battery-medium',
  'upload',
  'upload-cloud',
  'download',
  'file-text',
  'image',
  'music',
  'file',
  'folder-lock',
  'folder-plus',
  'hard-drive',
  'play',
  'pause',
  'shield-x',
  'triangle-alert',
  'layout-grid',
  'list',
  'type',
  'sun',
  'moon',
  'loader',
  'info',
]);

export const cognosIcons = Object.freeze({
  lock: Lock,
  'shield-check': ShieldCheck,
  shield: Shield,
  'key-round': KeyRound,
  'eye-off': EyeOff,
  search: Search,
  laptop: Laptop,
  plus: Plus,
  'message-square': MessageSquare,
  send: Send,
  paperclip: Paperclip,
  'book-text': BookText,
  sparkles: Sparkles,
  server: Server,
  cloud: Cloud,
  folder: Folder,
  'git-branch': GitBranch,
  landmark: Landmark,
  'graduation-cap': GraduationCap,
  users: Users,
  'user-plus': UserPlus,
  menu: Menu,
  'more-horizontal': MoreHorizontal,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  x: X,
  check: Check,
  pencil: Pencil,
  settings: Settings,
  'rotate-cw': RotateCw,
  copy: Copy,
  'copy-plus': CopyPlus,
  'refresh-cw': RefreshCw,
  'thumbs-up': ThumbsUp,
  quote: Quote,
  pin: Pin,
  link: Link,
  mail: Mail,
  'monitor-smartphone': MonitorSmartphone,
  eraser: Eraser,
  scale: Scale,
  languages: Languages,
  table: Table,
  signal: Signal,
  wifi: Wifi,
  'battery-medium': BatteryMedium,
  upload: Upload,
  'upload-cloud': UploadCloud,
  download: Download,
  'file-text': FileText,
  image: Image,
  music: Music,
  file: File,
  'folder-lock': FolderLock,
  'folder-plus': FolderPlus,
  'hard-drive': HardDrive,
  play: Play,
  pause: Pause,
  'shield-x': ShieldX,
  'triangle-alert': TriangleAlert,
  'layout-grid': LayoutGrid,
  list: List,
  type: Type,
  sun: Sun,
  moon: Moon,
  loader: Loader,
  info: Info,
});

export function getCognosIcon(name) {
  return cognosIcons[name];
}
