export type CognosIconNode = [
  tag: string,
  attrs: Record<string, string | number | undefined>,
][];

export type CognosIconName =
  | 'lock'
  | 'shield-check'
  | 'shield'
  | 'key-round'
  | 'eye'
  | 'eye-off'
  | 'search'
  | 'laptop'
  | 'plus'
  | 'message-square'
  | 'send'
  | 'paperclip'
  | 'book-text'
  | 'brain'
  | 'sparkles'
  | 'server'
  | 'cloud'
  | 'folder'
  | 'git-branch'
  | 'landmark'
  | 'graduation-cap'
  | 'users'
  | 'user-plus'
  | 'menu'
  | 'more-horizontal'
  | 'chevron-right'
  | 'chevron-down'
  | 'chevron-left'
  | 'x'
  | 'check'
  | 'pencil'
  | 'settings'
  | 'rotate-cw'
  | 'copy'
  | 'copy-plus'
  | 'credit-card'
  | 'calendar'
  | 'gauge'
  | 'refresh-cw'
  | 'thumbs-up'
  | 'quote'
  | 'pin'
  | 'link'
  | 'mail'
  | 'monitor-smartphone'
  | 'eraser'
  | 'scale'
  | 'languages'
  | 'table'
  | 'signal'
  | 'signal-high'
  | 'signal-low'
  | 'signal-medium'
  | 'signal-zero'
  | 'wifi'
  | 'battery-medium'
  | 'upload'
  | 'upload-cloud'
  | 'download'
  | 'file-text'
  | 'image'
  | 'music'
  | 'file'
  | 'folder-lock'
  | 'folder-plus'
  | 'hard-drive'
  | 'play'
  | 'pause'
  | 'shield-x'
  | 'triangle-alert'
  | 'layout-grid'
  | 'list'
  | 'type'
  | 'sun'
  | 'moon'
  | 'loader'
  | 'info';

export declare const cognosIconNames: readonly CognosIconName[];
export declare const cognosIcons: Readonly<Record<CognosIconName, CognosIconNode>>;
export declare function getCognosIcon(name: CognosIconName): CognosIconNode;
