---
openai:
  api_key: "sk-"
infomaniak:
  api_key: ""
  url: ""
  product_id: ""
cloudflare:
  api_key: ""
  account_id: ""
google:
  api_key: ""
anthropic:
  url: ""
  api_key: ""
deepinfra:
  url: ""
  api_key: ""
